os: osx
language: objective-c
osx_image: xcode9.3
# xcode_project: SwiftCommonMark.xcodeproj
# xcode_scheme: SwiftCommonMark

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

install:
  - brew upgrade swiftlint

script:
  - xcodebuild build test -project SwiftCommonMark.xcodeproj -scheme SwiftCommonMark CODE_SIGNING_REQUIRED=NO
    CODE_SIGN_IDENTITY=""

notifications:
  email: false

after_success:
  - bash <(curl -s https://codecov.io/bash)
