os: osx
language: objective-c
osx_image: xcode9.3
xcode_project: SwiftCommonMark.xcodeproj
xcode_scheme: SwiftCommonMark

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8

install:
- brew upgrade swiftlint

notifications:
  email: false

after_success:
- bash <(curl -s https://codecov.io/bash)
